name: Deploy to DigitalOcean Droplet (Staging & Production)

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy to Staging or Production
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "Deploying to production..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "bash /root/production_deploy.sh"
        elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
          echo "Deploying to staging..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} "bash /root/staging_deploy.sh"
        fi
